{{- if (.Values.serviceAccount | default dict).create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geolens.serviceAccountName" . }}
  labels:
    {{- include "geolens.labels" . | nindent 4 }}
  {{- with (.Values.serviceAccount | default dict).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
